import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configurar fonte local baixada
const Poppins = localFont({
  src: [
      {
          path: "../public/fonts/Poppins-Regular.ttf",
          weight: "400",
          style: "normal",
      },
      {
          path: "../public/fonts/Poppins-Bold.ttf",
          weight: "700",
          style: "normal",
      },
      {
        path: "../public/fonts/Poppins-SemiBold.ttf",
        weight: "500",
        style: "normal",
      }

  ],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
      <html lang="pt-BR" className={Poppins.variable}>
          <body className={Poppins.className}>
              <main>{children}</main>
          </body>
      </html>
  );
}




